services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: sentinel
      POSTGRES_PASSWORD: sentinel
      POSTGRES_DB: sentinel
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sentinel"]
      interval: 5s
      timeout: 3s
      retries: 5

  payment-service:
    build: ./payment-service
    ports:
      - "8002:8002"
    environment:
      PORT: 8002

  order-service:
    build: ./order-service
    ports:
      - "8001:8001"
    environment:
      PORT: 8001
      DATABASE_URL: postgresql://sentinel:sentinel@postgres:5432/sentinel
      PAYMENT_SERVICE_URL: http://payment-service:8002
    depends_on:
      postgres:
        condition: service_healthy
      payment-service:
        condition: service_started

  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      ORDER_SERVICE_URL: http://order-service:8001
      PAYMENT_SERVICE_URL: http://payment-service:8002
    depends_on:
      - order-service
      - payment-service

  traffic-generator:
    build: ./traffic-generator
    environment:
      GATEWAY_URL: http://gateway:8000
      REQUESTS_PER_SECOND: 3
    depends_on:
      - gateway

  prometheus:
    image: prom/prometheus:v2.54.1
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - order-service
      - payment-service

  grafana:
    image: grafana/grafana:11.1.0
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    volumes:
      - ./observability/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus

  detector:
    build: ./detector
    ports:
      - "8003:8003"
    environment:
      PROMETHEUS_URL: http://prometheus:9090
    depends_on:
      - prometheus

  ai-agent:
    build: ./ai-agent
    ports:
      - "8004:8004"
    environment:
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      PROMETHEUS_URL: http://prometheus:9090
      DETECTOR_URL: http://detector:8003
      PAYMENT_SERVICE_URL: http://payment-service:8002
    depends_on:
      - detector

volumes:
  pgdata:
